import user1 from '../assets/Image@2x.png';
import user2 from '../assets/Image-1.png';
import vender from '../assets/Image-2.png';

export const data =[
    {
        "type":"squad",
        "Order":25064,
        "user_image":user1,
        "name":"Tommy Hatcher",
        "address":"Eua Claire Wl 54701",
        "contact":"+1916-349-9454",
        "zip":50480,
        "orderTime":"3:12 PM",
        "vender":vender,
        "rider":"Bill Cohen",
        "amount":123,
        "performance":""
    },
    {
        "type":"normal",
        "Order":25064,
        "user_image":user2,
        "name":"Natasha",
        "address":"Eua Claire Wl 54701",
        "contact":"+1916-349-9454",
        "zip":50480,
        "orderTime":"3:12 PM",
        "vender":vender,
        "rider":"Bill Cohen",
        "amount":87,
        "performance":""
    },
    {
        "type":"normal",
        "Order":25064,
        "user_image":user1,
        "name":"Hillary",
        "address":"Eua Claire Wl 54701",
        "contact":"+1916-349-9454",
        "zip":50480,
        "orderTime":"3:12 PM",
        "vender":vender,
        "rider":"Bill Cohen",
        "amount":95.50,
        "performance":""
    },
    {
        "type":"normal",
        "Order":25064,
        "user_image":user1,
        "name":"Hillary",
        "address":"Eua Claire Wl 54701",
        "contact":"+1916-349-9454",
        "zip":50480,
        "orderTime":"3:12 PM",
        "vender":vender,
        "rider":"Bill Cohen",
        "amount":95.5,
        "performance":""
    },
    {
        "type":"normal",
        "Order":25064,
        "user_image":user1,
        "name":"Hillary",
        "address":"Eua Claire Wl 54701",
        "contact":"+1916-349-9454",
        "zip":50480,
        "orderTime":"3:12 PM",
        "vender":vender,
        "rider":"Bill Cohen",
        "amount":95.5,
        "performance":""
    },
    {
        "type":"normal",
        "Order":25064,
        "user_image":user1,
        "name":"Hillary",
        "address":"Eua Claire Wl 54701",
        "contact":"+1916-349-9454",
        "zip":50480,
        "orderTime":"3:12 PM",
        "vender":vender,
        "rider":"Bill Cohen",
        "amount":95.5,
        "performance":""
    },
    {
        "type":"squad",
        "Order":25064,
        "user_image":user1,
        "name":"Hillary",
        "address":"Eua Claire Wl 54701",
        "contact":"+1916-349-9454",
        "zip":50480,
        "orderTime":"3:12 PM",
        "vender":vender,
        "rider":"Bill Cohen",
        "amount":95.5,
        "performance":""
    },
    {
        "type":"squad",
        "Order":25064,
        "user_image":user1,
        "name":"Hillary",
        "address":"Eua Claire Wl 54701",
        "contact":"+1916-349-9454",
        "zip":50480,
        "orderTime":"3:12 PM",
        "vender":vender,
        "rider":"Bill Cohen",
        "amount":95.5,
        "performance":""
    },
    {
        "type":"normal",
        "Order":25064,
        "user_image":user1,
        "name":"Hillary",
        "address":"Eua Claire Wl 54701",
        "contact":"+1916-349-9454",
        "zip":50480,
        "orderTime":"3:12 PM",
        "vender":vender,
        "rider":"Bill Cohen",
        "amount":95.5,
        "performance":""
    },
    {
        "type":"squad",
        "Order":25064,
        "user_image":user1,
        "name":"Hillary",
        "address":"Eua Claire Wl 54701",
        "contact":"+1916-349-9454",
        "zip":50480,
        "orderTime":"3:12 PM",
        "vender":vender,
        "rider":"Bill Cohen",
        "amount":95.5,
        "performance":""
    },
    {
        "type":"squad",
        "Order":25064,
        "user_image":user1,
        "name":"Hillary",
        "address":"Eua Claire Wl 54701",
        "contact":"+1916-349-9454",
        "zip":50480,
        "orderTime":"3:12 PM",
        "vender":vender,
        "rider":"Bill Cohen",
        "amount":95.5,
        "performance":""
    },
]